/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#001f26",
        "surface-variant": "#d3e4fe",
        "on-primary-container": "#7d8497",
        "on-background": "#0b1c30",
        "outline-variant": "#c6c6cd",
        "surface-container-high": "#dce9ff",
        "inverse-surface": "#213145",
        "tertiary-container": "#001f26",
        "on-secondary-fixed-variant": "#004395",
        "on-tertiary-fixed-variant": "#004e5c",
        "inverse-primary": "#c0c6db",
        "secondary-fixed-dim": "#adc6ff",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-container": "#fefcff",
        "surface-container": "#e5eeff",
        "surface-bright": "#f8f9ff",
        "on-surface-variant": "#45464c",
        tertiary: "#000000",
        "primary-fixed": "#dce2f8",
        "error-container": "#ffdad6",
        secondary: "#0058be",
        error: "#ba1a1a",
        "secondary-container": "#2170e4",
        "surface-dim": "#cbdbf5",
        outline: "#76777d",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#4cd7f6",
        "surface-tint": "#575e70",
        "on-tertiary-container": "#0090a9",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed": "#001a42",
        "surface-container-low": "#eff4ff",
        "primary-container": "#151b2b",
        "on-primary-fixed": "#151b2b",
        "primary-fixed-dim": "#c0c6db",
        "secondary-fixed": "#d8e2ff",
        background: "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#acedff",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed-variant": "#404758",
        "on-surface": "#0b1c30",
        primary: "#000000",
        surface: "#f8f9ff",
        // Convenience aliases
        success: "#10b981",
        "success-container": "#d1fae5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-padding": "24px",
        gutter: "16px",
        unit: "4px",
      },
      fontFamily: {
        sans: ["'Geist'", "system-ui", "-apple-system", "sans-serif"],
        "display-lg": ["Geist"],
        "label-md": ["Geist"],
        "body-sm": ["Geist"],
        "body-lg": ["Geist"],
        "body-md": ["Geist"],
        "headline-sm": ["Geist"],
        "headline-md": ["Geist"],
        "headline-lg": ["Geist"],
        "mono-data": ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "label-md": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.02em",
            fontWeight: "500",
          },
        ],
        "body-sm": [
          "14px",
          {
            lineHeight: "20px",
            fontWeight: "400",
          },
        ],
        "body-lg": [
          "18px",
          {
            lineHeight: "28px",
            fontWeight: "400",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "24px",
            fontWeight: "400",
          },
        ],
        "headline-sm": [
          "20px",
          {
            lineHeight: "28px",
            fontWeight: "600",
          },
        ],
        "mono-data": [
          "14px",
          {
            lineHeight: "20px",
            fontWeight: "500",
          },
        ],
        "headline-md": [
          "24px",
          {
            lineHeight: "32px",
            fontWeight: "600",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
      },
      boxShadow: {
        card: "0px 4px 20px rgba(11, 18, 33, 0.05)",
        modal: "0px 12px 48px rgba(11, 18, 33, 0.12)",
        "glow-blue": "0 0 20px rgba(0, 88, 190, 0.35)",
      },
    },
  },
  plugins: [],
};
